### ISSUE TITLE
How to append/insert container/value (in)to document?

### ISSUE THREAD

**Issue by flying-sheep** [vosen/toml_document#1]
i don’t see any API to manipulate a Document at the top level

**Comment by vosen** [comment]
I've implemented string insertion today, but rest is work in progress. You can see the usage [here](https://github.com/vosen/toml_document/commit/b632709549a2b4c18200cd7d3ff2def47f29b8ef#diff-aeb5671119ce0cf0dd8c8f053eb7dc33R1067).
Table below shows what I'm lacking for 0.1. I'll be updating it as I implement missing stuff.

|  | document | inline table | table | inline array |
| --- | --- | --- | --- | --- |
| `insert_string` | :white_check_mark: | :white_check_mark: | :white_check_mark: | :white_check_mark: |
| `insert_integer` | :white_check_mark: | :white_check_mark: | :white_check_mark: | :white_check_mark: |
| `insert_float` | :white_check_mark: | :white_check_mark: | :white_check_mark: | :white_check_mark: |
| `insert_boolean` | :white_check_mark: | :white_check_mark: | :white_check_mark: | :white_check_mark: |
| `insert_datetime` | :white_check_mark: | :white_check_mark: | :white_check_mark: | :white_check_mark: |
| `insert_array` | :white_check_mark: | :white_check_mark: | :white_check_mark: | :white_check_mark: |
| `insert_inline_table` | :white_check_mark: | :white_check_mark: | :white_check_mark: | :white_check_mark: |
| `remove` | :white_check_mark: | :white_check_mark: | :white_check_mark: | :white_check_mark: |
| `insert_container` | :white_check_mark: | :no_entry: | :no_entry: | :no_entry: |
| `find` | :white_check_mark: | :white_check_mark: | :white_check_mark: | :white_check_mark: |

**Comment by vosen** [comment]
I've pushed 0.1 to crates that implements all basic find/insert/remove operations.
